#!/usr/bin/env python3
"""Write a stable, reviewable maintenance summary; dates live in Actions run metadata."""
import json
from pathlib import Path
import sys
report = json.loads(Path(sys.argv[1]).read_text())
lines = ['# Official upstream maintenance', '', 'Generated by the scheduled maintenance workflow. No upstream scripts are executed during collection.', '', 'Endpoint checks are unauthenticated HTTP observations, not a successful MCP authorization or tool test.', '', '| Plugin | Result | Source |', '| --- | --- | --- |']
counts = {}
for name, plugin in report['plugins'].items():
    if not plugin['checks']:
        lines.append(f'| {name} | manual-source-review | No machine-readable upstream configured |')
    for check in plugin['checks']:
        status = check['state']; counts[status] = counts.get(status, 0) + 1
        if status == 'unchanged': continue
        monitor = check['monitor']; result = check['result']
        source = monitor.get('repository') or monitor.get('url') or monitor.get('package')
        detail = result.get('error') or result.get('revision') or result.get('version') or result.get('status')
        detail = str(detail).replace('|', '\\|').replace('\n', ' ')
        lines.append(f'| {name} | {status}: {detail} | {source} |')
lines += ['', 'Counts: ' + ', '.join(f'{k}={v}' for k, v in sorted(counts.items())), '', '## Prepared package updates', '']
for update in report['applied']:
    lines += [f'- {update["plugin"]}: `{update["revision"]}` — review required.']
if not report['applied']: lines += ['No mapped package updates in this run. Unmapped updates require an explicit adapter mapping or a reviewed importer change.']
lines += ['', 'Merge only after CI passes and changes to scripts, instructions, license and runtime requirements have been reviewed. Production account functionality is not inferred from package checks.', '']
Path('maintenance/UPDATES.md').write_text('\n'.join(lines))
